openapi: 3.1.0
info:
  version: '1'
  title: API
tags:
  - name: Projects
    description: ''
  - name: Products
    description: ''
servers:
  - url: https://api.phixer.net/
security:
  - apiKey_header: []
paths:
  /v1/projects:
    $ref: paths/v1_projects.yaml
  /v1/projects/{projectId}:
    $ref: paths/v1_projects_{projectId}.yaml
  /v1/products:
    $ref: paths/v1_products.yaml
components:
  securitySchemes:
    apiKey_header:
      type: apiKey
      in: header
      name: Authorization
      description: >-
        An API key that will be supplied in a named header.
        https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#security-scheme-object
