type: object
properties:
  id:
    type: string
    description: ID of the product.
  name:
    type: string
    description: The name of the product.
  type:
    type: string
    description: Type of the product.
    enum:
      - EDITING_STYLE
      - TURNAROUND_TIME
